### ISSUE TITLE
Question: Is this in a stable state?

### ISSUE THREAD

**Issue by CreamyCookie** [edvin/tornadofx2#10]
The readme doesn't really address whether it is stable enough (and not likely to change that much).

Thanks for tornadofx @edvin !

**Comment by ChasDouglass** [comment]
Is it even active?  I love tornadofx but its been 3 years since java 9 was released.

**Comment by edvin** [comment]
It's active in the sense that I'm still here, just don't have time to work on it at the moment. @ctadlock has done a lot of work to prepare the 2.0 release though, and as far as I know it's production ready, and even used in production by several. My work situation leaves little time for TornadoFX at the moment, though we still use it heavily at work and I intend to move it forward when I need to at work, unless somebody beats me to it :) Help wanted!

**Comment by ChasDouglass** [comment]
Good to know, and thanks for replying.
Can 2.0 be put in a central maven repo?  Or am I just looking in the wrong one?

**Comment by edvin** [comment]
My pleasure. It's in oss.sonatype.org :)

**Comment by ChasDouglass** [comment]
Thanks!

**Comment by SchweinchenFuntik** [comment]
@CreamyCookie if you received an answer to your question, please close

**Comment by CreamyCookie** [comment]
Thanks for the answer!
