### ISSUE TITLE
Dialogs move to lower right each time they are opened

### ISSUE THREAD

**Issue by the-rene** [edvin/tornadofx2#31]
Each time an existing instance of a View is opened as a dialog, it is displayed lower and more to the right then before.  

A newly created instance works as excpected and is rendered at the same position each time. 

See the code below to reproduce this issue and the gif to show the behavior

```kotlin
import tornadofx.*

class MyMainView : View("main") {

    override val root = buttonbar {
        minHeight = 50.0
        minWidth = 200.0
        button("find dialog").action { find<MyDialog>().apply { openModal() } }
        button("new dialog").action { MyDialog().apply { openModal() } }
    }
}

class MyDialog : View("dialog") {
    override val root = buttonbar {
        minHeight = 50.0
        minWidth = 100.0
        button("close").action { close() }
    }
}

class MyApp : App(MyMainView::class)
fun main() = launch<MyApp>()
```

![tornadofx2_dialog](https://user-images.githubusercontent.com/8928240/113766699-02fed400-971e-11eb-9b82-4c31218b77b6.gif)

**Comment by SKeeneCode** [comment]
Verified, looks like a simple fix. Will work on PR.

**Comment by the-rene** [comment]
I can confirm the PR fixes this.

Thanks a lot for the quick response and fix!
