### ISSUE TITLE
Is this framework still maintained?

### ISSUE THREAD

**Issue by Anivie** [edvin/tornadofx2#53]
Has the author abandoned this maintenance? Will new features be added in the future(Such as turn off typesafe CSS to be compatible with native-image?)?

**Comment by edvin** [comment]
I personally are not working actively on the project at the moment, though others are. It's not yet decided if I'll return to active maintenance of TornadoFX. Time will tell. The project is still in good shape, and I'm around if there is anything critical. I'd love for someone to take a more active role in the project.
