### ISSUE TITLE
version javafx

### ISSUE THREAD

**Issue by SchweinchenFuntik** [edvin/tornadofx2#6]
Why is the minimum version of javafx 13? By what criteria was such a choice made?

**Comment by ctadlock** [comment]
Good question. I just pulled over what was was in v1.

@edvin thoughts?

**Comment by edvin** [comment]
Since JavaFX 11 is LTS, it might be good to go with that for now, unless it makes TornadoFX unusable with newer versions of JavaFX.

**Comment by ctadlock** [comment]
Is there a way to have this application driven? I'd like to use JavaFX 13 in my app, but not everyone will. Im not a Maven expert.

**Comment by SchweinchenFuntik** [comment]
version can be upgraded

**Comment by SchweinchenFuntik** [comment]
You can also make different modules for different versions, highlighting the basic features in the main core module.
Now many do it

**Comment by ruckustboom** [comment]
Other than the fact that it's LTS, is there any reason to stick with 11? Since TFX doesn't follow any sort of release cadence (let alone an LTS version), I don't really see how that's helpful to us (or the users). Using the latest stable version will give better performance and more features, and since Java 11 there's no need for the JavaFX version to match the JDK version, so we shouldn't have any sort of compatibility issues.

**Comment by SchweinchenFuntik** [comment]
What optimizations does the new version provide, maximum fix bugs? You probably do not understand what LTS is, 13 is already outdated, now you need to use 14 more.

After version 11, reflection continues to close. Bug with dirtyCell not fixed at 11, https://github.com/edvin/tornadofx/issues/1236

Are you sure you are ready to be released every month? I see nothing that there are 13 versions, except for the pain of use

**Comment by SchweinchenFuntik** [comment]
What will happen to jdk10 branch?

**Comment by edvin** [comment]
That makes sense @ruckustboom - we can compile against the latest release that works well for us, and users can use whatever version they feel like. So - we target JavaFX 14 now then I guess?

**Comment by edvin** [comment]
@SchweinchenFuntik https://github.com/edvin/tornadofx2 is "the new jdk10" branch, from which we'll soon release version 2.0.0 :)

**Comment by ruckustboom** [comment]
The reflection changes are a good reason why we should go with the latest version. If we compile against 11, but a user wants to use a later version (for example, so they can use the new native rendering buffers or e-ink displays), they could run into issues we didn't account for, but if we compile against the latest, we don't have to worry about it.

Sure, if we don't go with LTS we should update to 14. My argument wasn't that we should stay on 13 (I specifically said latest stable, not 13), just that I don't see why we should stay on LTS. I do understand what LTS is. What in my comment made you think I don't?

I'm not sure what you mean "except for the pain of use". We don't need to release a new version of TFX every time a new JavaFX version comes out, just make sure when we release a version, it's using the latest stable.

To be clear, this isn't a hill I'm willing to die on. I'm just giving my input.

**Comment by edvin** [comment]
I agree with @ruckustboom, it doesn't really make any sense to stay with 11. Let's go for 14, and keep targeting the latest version that we can comfortably compile against.

**Comment by SchweinchenFuntik** [comment]
close the question?
