### ISSUE TITLE
Migrating to Gradle Builds

### ISSUE THREAD

**Issue by yevhenii8** [edvin/tornadofx2#7]
Each time I wanted to drill down to under-hood of `tornadoFX` in order just to investigate how it works\to play with code\investigate a bug I was stopped by Maven and it still makes me cry (Am I the only one?) 
I have nothing against mvn in tornadofx (as it was created in 2016). But could switching to gradle be at least considered\investigated for tornadofx2 ? I think there's no need in pointing out why gradle is better than mvn and for this project in particular. I would like to outline only two items:

1. Most of tornadofx users are Kotlin developers and incidentally most of them are gradle users as well :)
2. Download gradle-based project, switch dependency from remote repository to local gradle project and that's it. It would simplify life for potential future contributors.

I would appreciate any thoughts about this. Thank you!

**Comment by SKeeneCode** [comment]
Now that tornadofx2 is gradle based - we should close this.

**Comment by yevhenii8** [comment]
Thanks to everyone who was involved!
